openapi: 3.0.1
info:
  title: SampleChoreoAPI
  description: API Definition of SampleChoreoAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/sample1
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /sampleRes2:
    get:
      responses:
        default:
          description: Default response
